<?php

namespace App\Exceptions;

use Exception;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Illuminate\Foundation\Http\Exceptions\MaintenanceModeException;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Schema;
use SkylarkSoft\GoRMG\SystemSettings\Services\LogToDB;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * A list of the exception types that are not reported.
     *
     * @var array
     */
    protected $dontReport = [
        //
    ];

    /**
     * A list of the inputs that are never flashed for validation exceptions.
     *
     * @var array
     */
    protected $dontFlash = [
        'password',
        'password_confirmation',
    ];

    public function report(Throwable $e)
    {
        if (Schema::hasTable('logs')) {
            LogToDB::log([
                "message" => $e->getMessage() . " On " . $e->getLine(),
                "code" => Response::HTTP_INTERNAL_SERVER_ERROR,
                "url" => request()->fullUrl(),
                "method" => request()->method(),
            ]);
        }

        return parent::report($e); // TODO: Change the autogenerated stub
    }

    /**
     * Register the exception handling callbacks for the application.
     *
     * @return void
     */
    public function register()
    {
        $this->reportable(function (Throwable $e) {
            //
        });
    }
}
